### ISSUE TITLE
Is it possible to select an audio output device?

### ISSUE THREAD

**Issue by michaeltheory** [LabSound/LabSound#112]
Hi there,

I've been looking at using this in my project. We have encountered situations where we need to output to a specific virtual sound card. It's possible in a [browser through WebRTC](https://webrtc.github.io/samples/src/content/devices/multi/).

Is it possible to do something like that with LabSound?

**Comment by meshula** [comment]
Technically yes. If you have a look here

https://github.com/LabSound/LabSound/blob/master/src/backends/windows/AudioDestinationWindows.cpp#L76

we are using the RtAudio default audio device. It should be possible use RtAudio to find the device you want, but you'll need to modify that code for now. Details are here:

http://web.mit.edu/carrien/Public/speechlab/marc_code/ADAPT_VC/rtaudio/doc/html/index.html#probing

If you are able to work that through a PR would be welcome, otherwise I can take a look after a couple of other issues are resolved.

**Comment by ddiakopoulos** [comment]
Working on an API for this.

**Comment by meshula** [comment]
Hi @ddiakopoulos, I was wondering if you had an update or a proposal for an API? This one would be great to have for installations.

**Comment by meshula** [comment]
@michaeltheory a year later --- the device_api_wpi branch has a device selection API in test.

**Comment by meshula** [comment]
merged to master
