### ISSUE TITLE
SampledAudioNode::schedule(double when) should use absolute time

### ISSUE THREAD

**Issue by xioxin** [LabSound/LabSound#153]
I can't schedule the playing time precisely

> The time, in seconds, at which the sound should begin to play, in the same time coordinate system used by the AudioContext.
> <https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/start>

**Comment by xioxin** [comment]
I didn't fully understand the working logic and I tried to modify it a bit.

Modified location https://github.com/LabSound/LabSound/blob/main/src/core/SampledAudioNode.cpp#L380

![image](https://user-images.githubusercontent.com/5716100/119222879-14166f80-bb29-11eb-85d9-da5b5a144c08.png)

**Comment by meshula** [comment]
The reason it's confusing is that schedule and start are not the same.

https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/start

start exercises the AudioScheduledNode base API. schedule() is a new that exposes the enhanced behavior of the SampledAudioNode, which has a different behavior than the ABSN. The ABSN has the behavior that it can only be played once, whereas the SAN can be played many times. schedule implements the following extra behavior that introduces granulation, and looping:

```cpp
    // loopCount of -1 will loop forever
    // all the schedule routines will call start(0) if necessary, so that a
    // schedule is sufficient for this node to start producing a signal.
    void schedule(double when);
    void schedule(double when, int loopCount);
    void schedule(double when, double grainOffset, int loopCount);
    void schedule(double when, double grainOffset, double grainDuration, int loopCount);
```

schedule(double when) is a relative time to the current time, equivalent to start(audioCtx.currentTime, when).

I notice that LabSound's AudioScheduledSourceNode has an error:

```cpp
    // Start time, measured as seconds from the current epochal time
    void start(float when) { _scheduler.start(when); }
```

We have used when, but should have used the term offset. The API should be:

```cpp
    // when is an  absolute time to start, in seconds, in the global epochal time
    // offset is the start time, in seconds, relative to when.
    void start(double when, double offset);
```

This demo https://github.com/LabSound/LabSoundDemo/blob/a988ee590fbb0bf0de1e0c32bf9cc6cb5fd784d7/LabSoundInteractive.cpp#L977 shows schedule in use.

If we add the missing start(when, offset) function, will that address the compatibility issue you are facing?

**Comment by meshula** [comment]
Note also, that LabSound doesn't implement an explicit AudioBufferSourceNode, because the auto-garbage collecting nature of it is not an obvious match to a C++ API. So far, implementors of WebAudio for JavaScript using LabSound have been using the SampledAudioNode to implement it, because it makes more sense to manage the garbage collected nature of the node in the language bindings.

A previous discussion is here: https://github.com/LabSound/LabSound/issues/139

**Comment by meshula** [comment]
A previous note on unexpected behavior of start is here: https://github.com/LabSound/LabSound/issues/139 @tom-23 Just to let you know, we're reopening this issue, if you'd like to keep tabs on it.

**Comment by xioxin** [comment]
Sorry, I mistakenly thought that "schedule" was an alternative to "start".
Adding the "offset" parameter will solve my problem.

I have looked into the "schedule" function and it is very nice.

I think "schedule" should not automatically execute "start". Otherwise "start" will be useless.

https://github.com/LabSound/LabSound/blob/d8386fc85e4a26f523d4674d95a71276a46adc07/src/core/SampledAudioNode.cpp#L130-L131

**Comment by xioxin** [comment]
```cpp
sampled->schedule(0., 2.0, 1);
sampled->start(audioContext->currentTime + 1.0);
```
This is a temporary solution for the "start" method without the "offset" parameter.

If the "start" method has an "offset" parameter, it is possible to play the specified position without adjusting the schedule.

**Comment by meshula** [comment]
Oh wait, I just re-read the offset documentation.

"An offset, specified as the number of seconds in the same time coordinate system as the AudioContext, to the time within the audio buffer that playback should begin. For example, to start playback halfway through a 10-second audio clip, offset should be 5."

This schedule API is almost the same, except it allows looping a certain number of times, instead of looping being binary on or off.

```
void schedule(double when, double grainOffset, double grainDuration, int loopCount);
```
I see your point about the confusion added by schedule calling start. I'm taking a look at cleaning up that up now.

**Comment by meshula** [comment]
https://github.com/LabSound/LabSound/commit/99f9eec387fa7f7e6533d455198ee59dcec9c79c

**Comment by meshula** [comment]
Looks like we've "autoclose" turned on... 

Anyway, https://github.com/LabSound/LabSound/commit/99f9eec387fa7f7e6533d455198ee59dcec9c79c adds start methods to the SampledAudioNode, including start with offset and duration, and loop count. The schedule functions are relative, the start functions are absolute, but otherwise they now both behave the same way. Note that I did not change start on the ScheduledSampleNode, because that would affect behavior for all nodes.

So, start(when), must be called on a SampledAudioNode pointer, not the base pointer, because start is not virtual.

Let me know if this gets you going.

**Comment by xioxin** [comment]
Thanks, it solved my problem
