### ISSUE TITLE
AudioBufferSourceNode

### ISSUE THREAD

**Issue by Larpoux** [LabSound/LabSound#172]
Hi everybody.
I have a stupid question : 
How can I create an [AudioBufferSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode) ?
Is there somewhere a table with how the W3C recommandation match the LabSound library?
Thank you guys /girls and others. Take care.

**Comment by meshula** [comment]
In general the LabSound library match the W3C recommendations, but does not include anything to do with Worklets, since that mechanism is not obviously portable to a C++ library. PRs and issues are welcome to address compatibility with the spec.

This issue https://github.com/LabSound/LabSound/issues/73 has background discussion on the absn, and why it was lost during a refactoring of the code. That thread talks about how to re-introduce the absn using the SampledAudioNode, and AudioBus. The AudioBufferSoundNode could be written as a subclass of SampledAudioNode that reintroduces the specific absn concepts. After the discussion in that thread, the request didn't come up again, as the various js/node bindings around LabSound implement the ABSN in the binding.

Happy to have it back in the library formally, although nothing is planned for it right now.

**Comment by Larpoux** [comment]
Thank you @meshula
