### ISSUE TITLE
Doppler working?

### ISSUE THREAD

**Issue by dug9** [LabSound/LabSound#178]
When using PannerNode, I can print the doppler rate
                    ContextRenderLock r(&context, "ex_simple");
                    float dr = pannerNode_ptr->dopplerRate(r);
                    std::cout << " doppRate " << dr << std::endl;
 and it looks interesting and useful.
 doppRate 1.40937
 vel= 70.3304 0 157.708
 ...
doppRate 0.891119
 vel= 164.346 0 -52.9939
 ...
 But I don't hear a frequency shift. And I don't see anything in labsound using the computed dopplerRate. How is it supposed to work, is it something more I need to do in my application code beyond setting panner velocity?
pannerNode_ptr->setVelocity(v[0], v[1], v[2]);
Thanks

**Comment by dug9** [comment]
With my current application using web3d format, listeners are parent nodes and sources are children or grandchildren. I can push a dopplerFactor=1 onto a stack, and if there's a PannerNode in the scenegraph, I can getDopplerFactor() and push that onto the stack before processing its children. When I get to a SampledAudioNode I can peek at my dopplerFactor stack value and multiply by any other pitch settings
            audioClipNode_ptr->playbackRate()->setValue(pnode->pitch*srepn->dopplerFactor);
Then pop going back.
I get a big doppler effect.
Is this a good way to do it?

**Comment by meshula** [comment]
Yes, a pull request like that would be welcome.

It will miss OscillatorNodes and others. What are the expectations on doppler for other node types?

**Comment by dug9** [comment]
Ideally oscillators traveling with PannerNode (and other source nodes?) would get the pitch change. Oscillators have a .frequency field, perhaps that can be modified at runtime similar to pitch?

**Comment by meshula** [comment]
Is it possible, in the case you are thinking of, that there might be more than one listener or panner connected to the same subgraph?

```
listener1 <-+--- osc1
            |
listener2 <-+
```
Currently the traversal of the signal graph assumes that osc1 only needs to be rendered once per quantum. But, two listeners would require two traversals of the shared subgraph.
Same issue for PannerNodes.

**Comment by dug9** [comment]
Interesting, good point, and in web3d there is a way to re-use a node at a different location in the scenegraph
Listener
- Panner1
-- DEF OSC1 Oscillator
- Panner2
-- USE OSC1
And while the oscillator would get 2 visits, the visits are close in computer time on the same 3D rendering frame, and the last visit would set the pitch / frequency heard for 99% of frame time. web3d..org wrl/x3d standard is for a 'prototyping language' meaning it's good for trying things out. So there can be edge cases that aren't well handled. But would be nice if we handled this case.
Q. is there a way to adjust the pitch for doppler that's associated with the PannerNode? Even if there was another intermediate node
Listener -connect- Panner -connect- (mystery pitch adjuster node) -connect- processingnode - connect -sourcenode
that would work for web3d. Or something that can be built into Panner.
Thanks

**Comment by meshula** [comment]
There's a fundamental problem with pitch shifting nodes, unless tney are highly restricted in how much they can shift pitch. The problem is that if you slow things down a lot, you potentially make an infinite buffer to hold all the previous sound (infinite because it just grows and grows and never catches up), or if you speed things up a lot, you potentially need huge buffers into the future of the upstream node. Implementing pitch shifting as you are suggesting, like on a sound buffer node, or on an oscillator avoids that problem.

On your second question, Doppler should be computed with the Listener and Panner nodes as input in order to compute a relative velocity. It sounds like the ideal solution would be a Doppler computing node, that has a relative velocity input, or a {pos1,vel1, pos2,vel1} input, and outputs a value for pitch shift that can be wired to an oscillator or sound buffer node.

the nice thing about such an intermediate mode, is that it would force the signal processing graph to make sense ~ one would have to be very intentional about setting up exactly what you want.

Previously, I would have suggested that perhaps on the WebAudio side, a Script Processing Node could have a tiny bit of Javascript in it to do the computation, but I think that the Script Processing Node was deprecated, so I'm not sure what the best solution would be today?

**Comment by meshula** [comment]
Of course, a Javascript program could also, once per frame, do the computation and manually set the pitch shift, and rely on WebAudio parameter interpolation to avoid popping artifacts.

**Comment by dug9** [comment]
Thanks for the analysis.  I'll close for now and keep what I'm doing, but if there's something more general in the future we can get back to it.
