### ISSUE TITLE
AudioNode::disconnect & AudioContext::disconnect

### ISSUE THREAD

**Issue by ddiakopoulos** [LabSound/LabSound#22]
Several lingering disconnect methods on AudioContext need to be tested

**Comment by meshula** [comment]
Do you recall particulars of this issue?

**Comment by ddiakopoulos** [comment]
Too long ago to remember, but just taking a look at some stuff has me like

![tumblr_o16n2kblpx1ta3qyvo1_1280](https://user-images.githubusercontent.com/871903/34550688-c7d1084e-f0c7-11e7-92b7-a721fc2a2076.jpg)

**Comment by ddiakopoulos** [comment]
There should be a way to coalesce connect/disconnect functions. 

Currently there are two variants:
  1. `std::shared_ptr<AudioNode>`
  2. `std::shared_ptr<AudioNodeInput>` and `std::shared_ptr<AudioNodeOutput>`

Of these, item 1 is put through the little connection/disconnection reference counter, but `AudioNodeInput` and `AudioNodeOutput`s are connected straight away. 

There's something awkward here, but it's been a while since I've dug into this part of the code. Any light to shed?

**Comment by meshula** [comment]
The refcount on the audio nodes has to go, that's for sure. The double delegation of connect and disconnect has to go too. I vaguely recall I was half way through that clean up, and the first step was to get the nodes to delegate through the context. eg.

    void AudioNode::disconnect(AudioContext * ctx)
    {
        for (auto & output : m_outputs)
            ctx->disconnect(output);
    }

The next step should be to squash it all down.  I had moved all the connect/disconnect logic to update so that the signal graph could be modified on the fly. The WebAudio engine at the time I forked it didn't tolerate modifying a live graph.

Looking at void AudioContext::update(ContextGraphLock& g), it looks like I was half way through the work. That said, in your case 2, the ref count is raised and lowered, and the connections are only supposed to be done by update. The code design doesn't express that at all.

Also, there are also way too many shared_ptrs in teh party. I don't think there's any retain cycles, but still.

**Comment by ddiakopoulos** [comment]
Alrighty! https://github.com/LabSound/LabSound/tree/connect-disconnect-refactor

We're on the same page about all of that. I had a stab at it this morning (still have a couple days left before I start my new gig!).

There's one major public API change here. `AudioContext::connect` and `AudioContext::disconnect` are now the sole entrypoints for modifying the graph. Before going too far with this, I only changed a few of the examples (and also internal nodes) to reflect this style. 

Previously:
```
// osc -> gain -> destination
oscillator->connect(ac, gain.get(), 0, 0);
gain->connect(ac, context->destination().get(), 0, 0);
```

Now:
```
// osc -> gain -> destination
 ac->connect(gain, oscillator, 0, 0);
 ac->connect(context->destination(), gain, 0, 0);
```

What do you think?

**Comment by meshula** [comment]
Thanks for having a go!

That is infinitely more readable, and there's less code overall, so double win :) This would be a good point to version tag the library since the API change will require client code to change.

**Comment by modulesio** [comment]
@ddiakopoulos Re: this API change, what's the recommended way to handle WebAudio's "disconnect all" behavior, for example?

I see in the code that both `src` and `dst` indices are required.

**Comment by meshula** [comment]
@modulesio The new behavior is that if you call disconnect as follows

    ac->disconnect(myNode, {}, 0, 0);

myNode's outputs will be disconnected from anything listening to it

    ac->disconnect({}, myNode);

will disconnect myNode from anything it is listening too.

So disconnect all will require calling both.

    ac->disconnect(myNode, {}, 0, 0);
    ac->disconnect({}, myNode);

@ddiakopoulos Maybe we should introduce disconnectAll, or add a case for

    ac->disconnect(myNode, myNode);

**Comment by meshula** [comment]
closing as it's not clear we need to do anything else.
