### ISSUE TITLE
Factory for SoundBuffer?

### ISSUE THREAD

**Issue by meshula** [LabSound/LabSound#55]
The Android fork by @eleventigerssc suggests a need for SoundBuffer to take a more general approach to file loading. 

I'm hesitant to reintroduce factories to LabSound though. I feel like the one time that factories should be used is for when contained objects must be created, but those objects cannot have ownership outside of the containing object. In other words, when an owning object must maintain lifetime ownership of the produced object. 

Rather than going with a factory approach, perhaps SoundBuffer could take an asset loading lambda that resolves an asset reference into an array of bytes or something like that. 

Or, perhaps SoundBuffers could reasonably be considered the sort of object that shouldn't have external ownership, perhaps because they could be artifacts of something internal to the engine, in some cases, like if the SoundBuffer wraps a hardware resource?

Any thoughts?

**Comment by ddiakopoulos** [comment]
SoundBuffer is a real outlier to the rest of the codebase. I think it reveals an underlying problem there's no concept of an asset. To this end, I agree about the principled use of an asset loader / factory that owns and loans out the underlying resource: a library! 

There might be a hybrid approach here. Assuming the use of a string id as a handle:
```
static std::map<std::string, std::shared_ptr<audio_asset>> asset_library;
```

I started thinking about this for another project and have a half-working impl here: https://github.com/ddiakopoulos/sandbox/blob/master/virtual-reality/assets.hpp ... I would then add a loader lambda that produces an underlying `AudioBuffer` instead of the simplistic `register_asset(...)` that uses an rvalue reference. In theory get_asset could call the lamba to even enable lazy loading (although this is probably not that desirable in the context of realtime audio!)

The `asset_library` could even be templated on input type (ogg, wav, etc). This would make it maximally-platform independent and even libnyquist could be considered a non-core dependency.

**Comment by meshula** [comment]
That's promising. Your approach is very similar to Pixar's.

https://github.com/PixarAnimationStudios/USD/blob/master/pxr/usd/lib/ar/resolver.h

A resolver class like this could work cleanly with an asset library.

**Comment by meshula** [comment]
This issue is obsoleted by https://github.com/LabSound/LabSound/commit/501ef6c33274eed017b039a1cd2260f4c4cb9998
