### ISSUE TITLE
Calling Context::Disconnect causes audible click if rendering

### ISSUE THREAD

**Issue by ddiakopoulos** [LabSound/LabSound#62]
Even if node was not producing audio

**Comment by meshula** [comment]
in theory tailTime should handle this sort of thing, but it never took disconnect into account.

This sort of thing is usually caused by leaving the speaker cone at a certain deflection then suddenly moving it somewhere else. In iMuse, I solved this by setting a ten sample filter window when a discontinuity such as removing a node was introduced. The idea would be that as long as a certain count was above zero, the values written into the sample buffer would be low pass filtered for ten frames. I recall that at 44khz, 10 frames was enough to kill pops.

**Comment by meshula** [comment]
Is this still true, or was it solved by the scheduled disconnection?

**Comment by ddiakopoulos** [comment]
I will check!

**Comment by meshula** [comment]
The LiveGraphUpdate demo does not audibly click for me, I think the scheduled disconnection did the job. I'm closing this, please reopen if you hear it again.
