### ISSUE TITLE
language bindings directory organization - RFC

### ISSUE THREAD

**Issue by meshula** [LabSound/LabSound#68]
I've been thinking about language bindings.

@modulesio has started a node binding. I notice that the binding is at root, in a directory called lib. I suspect that this is a gyp convention on where code should be placed in order that the build system can find all the components.

Rust has a similar fixed directory layout when making crates.

I'm wondering if it might be an idea that language bindings are created referencing LabSound as a submodule, and then the projects might be named according to a convention, such as

````
labsound-rs
labsound-node
labsound-py
labsound-c
````
etc., with their required structure contained within?

**Comment by modulesio** [comment]
Sub modules sounds like a reasonable way.

I’m just experimenting for now though. I think fixing Linux and unifying builds on all platforms kind of needs to come first.

Currently working on Linux support.

**Comment by raub** [comment]
May be there is no need for an "official language XX binding" thing at all? Let LabSound be LabSound, and hope it'll do it in a right way. Meanwhile I build a Node.js binding [here](https://github.com/raub/node-waa). And the other day I saw some guy doing something else like that.

@meshula there's no GYP convention to put sources in a specific place, [see example](https://github.com/raub/node-waa/blob/87ad14d509c7f0966fd6b6ccb0317b16f4e25cf8/binding.gyp#L13) in my repo.

My own convention is to prebuild backend libs, such as LabSound or Bullet, and put them in a node module named ['deps-<lib name>-raub'](https://www.npmjs.com/package/deps-labsound-raub). Then the binding itself depends on this module. Ofcourse deps-labsound-raub could include LabSound as a submodule, but it is up to me whether I even like the submodules at all.

Now, my proposal is: if you've made a decent binding, file an issue to LabSound in order to get it reviewed and added to LabSound's README.md :wink:

**Comment by meshula** [comment]
closing, as submodules and PR's as @raub suggests should be fine.
