### ISSUE TITLE
RtAudio vs PortAudio (feature request)

### ISSUE THREAD

**Issue by johnwbyrd** [LabSound/LabSound#80]
What was the thinking on going with RtAudio vs. PortAudio as a base layer?

**Comment by meshula** [comment]
That's a great question. PortAudio and RtAudio both have much to recommend them. The original implementation was created with platforms in mind (Windows, macOS, Linux, etc.) RtAudio arrived as a way to flesh out the Windows implementation quickly, but it's clearly useful cross platform. At this point, I'd be inclined to say the way forward should be to organize the backends according to implementation, not platform. A nice approach would be a cmake variable that specifies which backend a user prefers.

I'd be open to PRs implementing new backends, such as PortAudio.

**Comment by johnwbyrd** [comment]
kthx, at some point I'll take a look at the complexity of a new backend implementation.

**Comment by ddiakopoulos** [comment]
I have one opinion on this: PortAudio is considerably harder to build, whereas RtAudio is just a few header files and a single cpp. There's also `libsoundio` which is new on the scene: http://libsound.io/

**Comment by meshula** [comment]
It makes more sense to organize by backend than platform overall, as there are many viable backends per platform. Linux users might like to choose between rtaudio, asound, alsa, or whatever for example.

As of this commit (https://github.com/LabSound/LabSound/commit/7357ca5267aefe75890d0c7d8517bf0bc7d83689) there is a backends directory, currently populated with linux, windows, and darwin (macos/ios). There could easily be an RtAudio backend directory, or a PortAudio backend. 

If a backend combo needs to be specially made, then a new triple-named directory (e.g. linux-rtaudio-asound) should be created rather than trying to wedge many implementations into a single linux directory.
