### ISSUE TITLE
AudioScheduledSourceNode onended?

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#85]
Hello again. I've been looking through the header of `AudioScheduledSourceNode` and found no mention of this event. When it ends, it ends, that's it.

However, there is a lot of (JS) code that expects `onended` calback to be called. For example [in three.js](https://github.com/mrdoob/three.js/blob/09c96d393d67486b71286d923c0feb4e1fe94ac3/src/audio/Audio.js#L86) it leads to the warning `'THREE.Audio: Audio is already playing.'`.

If there actually is such an event, please point me in a right direction. And if there are no events in LabSound, then how those should be implemented?

**Comment by ddiakopoulos** [comment]
You are correct, there's no callback for this. We should add a public API to `AudioScheduledSourceNode` to attach a `std::function` callback that would be triggered here: https://github.com/LabSound/LabSound/blob/master/src/core/AudioScheduledSourceNode.cpp#L147

**Comment by raub** [comment]
Also some user-data should be available, because on the other end you should know the context of the call.

**Comment by meshula** [comment]
I see there are seven possible events these days.

**Comment by raub** [comment]
I wonder whether this `finish()` is called on the main thread or not... I've tried to invoke some kind of callback from there and it unexpectedly resulted in later segfault 🤔

**Comment by meshula** [comment]
The callbacks shouldn't be invoked from methods with a renderlock. In terms of user data, lambdas or std::bind should do the trick.

**Comment by raub** [comment]
So, if we can't call it here https://github.com/LabSound/LabSound/blob/master/src/core/AudioScheduledSourceNode.cpp#L147 then where?

**Comment by meshula** [comment]
Here's an almost complete of a safe implementation of onended.

https://github.com/LabSound/LabSound/tree/callbacks
https://github.com/LabSound/LabSound/commit/c69a6771361ff3aed2596b20267dfaf1bd7613e4

To be complete, it needs a concurrent queue of some sort. The basic idea is that the audio context has a queue of events to fire. A node that wants to fire an event moves it's event to the queue while the renderlock is held. 

During the next audio context update, any pending events should be called. The event callbacks themselves should be written to be safe on the update thread.

The best implementation for the concurrent queue that I can think of right now is to double buffer two queues. Whenever update is called, it should atomically swap the two queues. That way, the rendering code will always have a safe queue to push events onto, and update doesn't have to lock the queue it is dispatching.

The code on the branch doesn't do that, it just shows how all the pieces would fit together.

**Comment by raub** [comment]
May be [this one](https://github.com/cameron314/concurrentqueue) is ok?

**Comment by ddiakopoulos** [comment]
We actually have one in LabSound already, but it was only formerly used for samples. I wouldn't mind bringing it into the core, it's simple: https://github.com/LabSound/LabSound/blob/master/examples/src/ConcurrentQueue.h

**Comment by raub** [comment]
Oh, that's very good. So what's the forecast?

I'd like to try it as soon as it gets implemented. Since you already have almost everything in place, I don't know how else I can help, but tell me if anything.

**Comment by meshula** [comment]
moodycamel's readerwriter queue is lockfree, and roughly O(1) for single producer single consumer. The ConcurrentQueue we use in the demos is mutex based, and mutexes can wreak havoc in the audio processing callback especially if the audio callback is invoked from an interrupt. Since the moodycamel implementation is based on atomic barriers, it should be both thread and IRQ safe, and also very fast.

I've pushed an implementation on the "callbacks" branch if anyone wants to try it out. https://github.com/LabSound/LabSound/commit/4e4302408770d89a1c666624073141e7babb33a6

**Comment by raub** [comment]
I've just tried it. And it almost works.

First, there seem to be missing `cv.notify_all();` thing in `AudioContext::enqueueEvent`. When I put it there, the callback fires.

Second,  `AudioContext::update` is most likely called within some worker thread. Which I can tell by observing a segfault. I need to know whether it is possible for LabSound to call the callback on behalf the main thread. Because I'll have to call JS callback and it is only possible within the main thread.

**Comment by meshula** [comment]
I pushed a working version, and a simple example app to show it working.

https://github.com/LabSound/LabSound/commit/b8dc1adeabddca2e63e634c7ce72a746436c2585

By default, the AudioContext will automatically dispatch the events from the update thread, because that's the easiest for an end user. It will be safe and legal for the user to add and remove nodes, and it won't cause audio glitching. 

I added a new optional parameter to the AudioContext constructor, to control whether you want the audio context to automatically dispatch the events on its thread, or if you want to be responsible for dispatching the events. If you want the events dispatched from your own thread, periodically call ac->dispatchEvents(). It'll return very quickly if there are no events.

Instead of an optional bool, we could have a second constructor that takes a reference to a condition variable. You'd have to write more complicated main loop logic to take advantage of that though, so I didn't go down that road.

If this approach looks good to you guys we can merge it.

**Comment by raub** [comment]
@meshula Are you sure that `std::lock_guard<std::mutex> lock(m_updateMutex);` is not needed here? Asking this just because I saw it in other methods alongside `notify_all`, for example in connect/disconnect...

**Comment by raub** [comment]
Tried the b8dc1ad, it seem to work properly. I have a JS example [here](https://github.com/raub/node-waa/blob/master/examples/_simple.js). The callback is called using `dispatchEvents()`.

**Comment by meshula** [comment]
done, merged to master.

**Comment by raub** [comment]
That's very good! 👍 

Also, I didn't mean to push WIP, when speaking about PR. PR is a good tool for the code review and feature tracking. You can simply create one and let it be. Then people can come and see, and comment. Then you push to this branch more changes, and they are displayed as a sort of history. To make it clear that PR is WIP, people usually prepend PR with "WIP: My awesome feature". Then nobody merges it accidentally.

**Comment by meshula** [comment]
Oh, sorry I misunderstood what you meant :]
